# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\01_Python_dev\05_수집툴통합관리\protoType.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import os
import subprocess
from qt_material import apply_stylesheet, QtStyleTools
import time
import schedule
from datetime import datetime, date, timedelta
import traceback
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.base import JobLookupError

DEFAULT_STYLE = """
QProgressBar{
    border: 2px solid grey;
    border-radius: 5px;
    text-align: center
}

QProgressBar::chunk {
    background-color: lightskyblue;
    width: 10px;
    margin: 1px;
}
"""
LIST_STYLE = """
QListWidget
{
border : 2px solid turquoise;
}
"""

today_day = date.today().day
today_month = date.today().month
today_year = date.today().year

dateDict = {0: '월', 1:'화', 2:'수', 3:'목', 4:'금', 5:'토', 6:'일'}
date = date.today()
datetime_date = datetime.strptime(str(date), '%Y-%m-%d')
today_date = dateDict[date.weekday()]


def getDate(y, m, d):
    '''y: year(4 digits)
     m: month(2 digits)
     d: day(2 digits'''
    s = f'{y:04d}-{m:02d}-{d:02d}'
    return datetime.strptime(s, '%Y-%m-%d')


def getWeekNo(y, m, d):
    target = getDate(y, m, d)
    firstday = target.replace(day=1)
    if firstday.weekday() == 6:
        origin = firstday
    elif firstday.weekday() < 3:
        origin = firstday - timedelta(days=firstday.weekday() + 1)
    else:
        origin = firstday + timedelta(days=6 - firstday.weekday())
    return (target - origin).days // 7 + 1

weekNum = getWeekNo(today_year, today_month, today_day)



now = datetime.now()
print(now)          # 2015-04-19 12:11:32.669083

nowDate = now.strftime('%Y-%m-%d')
print(nowDate)      # 2015-04-19

nowTime = now.strftime('%H:%M:%S')
print(nowTime)      # 12:11:32

nowDatetime = now.strftime('%Y-%m-%d %H:%M:%S')
print(nowDatetime)  # 2015-04-19 12:11:32