python ..\private_academy_pp.py private_academy_bs_utf8.txt 부산학원교습소_utf8.txt ansi ppname
python ..\private_academy_pp.py private_academy_cc_utf8.txt 충청학원교습소_utf8.txt ansi ppname
python ..\private_academy_pp.py private_academy_dg_utf8.txt 대구학원교습소_utf8.txt ansi ppname
python ..\private_academy_pp.py private_academy_dj_utf8.txt 대전학원교습소_utf8.txt ansi ppname
python ..\private_academy_pp.py private_academy_gg_utf8.txt 경기학원교습소_utf8.txt ansi ppname
python ..\private_academy_pp.py private_academy_gs_utf8.txt 경상학원교습소_utf8.txt ansi ppname
python ..\private_academy_pp.py private_academy_gw_utf8.txt 강원학원교습소_utf8.txt ansi ppname
python ..\private_academy_pp.py private_academy_ic_utf8.txt 인천학원교습소_utf8.txt ansi ppname
python ..\private_academy_pp.py private_academy_jj_utf8.txt 제주학원교습소_utf8.txt ansi ppname
python ..\private_academy_pp.py private_academy_sj_utf8.txt 세종학원교습소_utf8.txt ansi ppname
python ..\private_academy_pp.py private_academy_su_utf8.txt 서울학원교습소_utf8.txt ansi ppname
python ..\private_academy_pp.py private_academy_us_utf8.txt 울산학원교습소_utf8.txt ansi ppname
python ..\private_academy_pp.py private_academy_gj_utf8.txt 광주학원교습소_utf8.txt ansi ppname
#python ..\private_academy_pp.py private_academy_jr_utf8.txt 전라학원교습소_utf8.txt ansi ppname
python ..\private_academy_pp.py private_academy_jn_utf8.txt 전남학원교습소_utf8.txt ansi ppname
python ..\private_academy_pp.py private_academy_jb_utf8.txt 전북학원교습소_utf8.txt ansi ppname

#python ..\private_academy_pp.py file_jb0_utf8.txt 전북학원_utf8.txt ansi ppname
#python ..\private_academy_pp.py file_jb1_utf8.txt 전북교습소_utf8.txt ansi ppname
#python ..\private_academy_pp.py file_jn0_utf8.txt 전남학원_utf8.txt ansi ppname
#python ..\private_academy_pp.py file_jn1_utf8.txt 전남교습소_utf8.txt ansi ppname
