python 학원교습소정보2_광주.py > log.txt
python 학원교습소정보2_전남.py >> log.txt
python 학원교습소정보2_전북.py >> log.txt
python 학원교습소정보_강원.py >> log.txt
python 학원교습소정보_경기.py >> log.txt
python 학원교습소정보_경상남북.py >> log.txt
python 학원교습소정보_대구.py >> log.txt
python 학원교습소정보_대전.py >> log.txt
python 학원교습소정보_부산.py >> log.txt
python 학원교습소정보_서울.py >> log.txt
python 학원교습소정보_세종.py >> log.txt
python 학원교습소정보_울산.py >> log.txt
python 학원교습소정보_인천.py >> log.txt
python 학원교습소정보_제주.py >> log.txt
python 학원교습소정보_충청남북.py >> log.txt
