# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\00_DEV\05_수집툴통합관리\protoType.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import os
import subprocess

class Ui_Collect(object):
    def setupUi(self, Collect):
        Collect.setObjectName("Collect")
        Collect.resize(900, 250)
        self.gridLayout = QtWidgets.QGridLayout(Collect)
        self.gridLayout.setObjectName("gridLayout")
        self.close = QtWidgets.QPushButton(Collect)
        self.close.setObjectName("close")
        self.gridLayout.addWidget(self.close, 1, 3, 1, 1)
        self.start = QtWidgets.QPushButton(Collect)
        self.start.setObjectName("start")
        self.gridLayout.addWidget(self.start, 0, 3, 1, 1)
        self.collectList = QtWidgets.QTextEdit(Collect)
        self.collectList.setObjectName("collectList")
        self.gridLayout.addWidget(self.collectList, 2, 0, 1, 1)
        self.progressText = QtWidgets.QTextBrowser(Collect)
        self.progressText.setObjectName("progressText")
        self.gridLayout.addWidget(self.progressText, 2, 1, 1, 3)
        self.fileOpen = QtWidgets.QPushButton(Collect)
        self.fileOpen.setObjectName("fileOpen")
        self.gridLayout.addWidget(self.fileOpen, 0, 2, 1, 1)
        self.deleteView = QtWidgets.QPushButton(Collect)
        self.deleteView.setObjectName("deleteView")
        self.gridLayout.addWidget(self.deleteView, 1, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(Collect)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 0, 2, 2)

        self.fileOpen.clicked.connect(self.fileOpneButtonClick)
        self.start.clicked.connect(self.RunExeList)
        self.close.clicked.connect(QtCore.QCoreApplication.instance().quit)
        self.deleteView.clicked.connect(self.RemoveList)

        self.retranslateUi(Collect)
        QtCore.QMetaObject.connectSlotsByName(Collect)

    def retranslateUi(self, Collect):
        _translate = QtCore.QCoreApplication.translate
        Collect.setWindowTitle(_translate("Collect", "Collect_Manager"))
        self.fileOpen.setText(_translate("Collect", "수집 툴 불러오기"))
        self.deleteView.setText(_translate("Collect", "리스트 지우기"))
        self.start.setText(_translate("Collect", "시 작"))
        self.close.setText(_translate("Collect", "종 료"))

    def fileOpneButtonClick(self):
        file_name = QtWidgets.QFileDialog.getOpenFileNames()
        for file in file_name[0]:
            exist = self.collectList.toPlainText()
            self.collectList.setText(exist + file + '\n')
            with open('exe_list.txt', 'a') as f:
                f.write(file + '\n')
            f.close()

    def RunExeList(self):
        with open('exe_list.txt') as data:
            lines = data.read().splitlines()
        inputName = lines
        self.progressBar.setMaximum(len(inputName))
        count = 0
        for exe in inputName:
            count += 1
            self.progressBar.setValue(count)
            QtWidgets.QApplication.processEvents()
            self.progressText.append(exe + ' 수집')
            run = subprocess.Popen(exe)
            run.wait()
            QtWidgets.QApplication.processEvents()
        data.close()
        os.remove('exe_list.txt')
        self.progressText.append('전체 수집 종료')
        print('전체 수집 종료')

    def RemoveList(self):
        self.collectList.clear()
        self.progressText.clear()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Collect = QtWidgets.QWidget()
    ui = Ui_Collect()
    ui.setupUi(Collect)
    Collect.show()
    sys.exit(app.exec_())
