python hansdeli.py > log.txt
python mrpizza.py >> log.txt
python outback.py >> log.txt
python sevensprings.py >> log.txt
python sorrento.py >> log.txt
python tgifridays.py >> log.txt
python todai.py >> log.txt
python VIPS.py >> log.txt
python 도미노피자.py >> log.txt
python 무스쿠스.py >> log.txt
python 보노보노.py >> log.txt
python 이랜드계열_애슐리.py >> log.txt
python 카페아모제.py >> log.txt
python 피자헛.py >> log.txt
