python ..\general_pp.py adidas_utf8.txt ..\final\91002_브랜드신발_아디다스.txt ansi noop
python ..\general_pp.py asics_utf8.txt ..\final\91002_브랜드신발_아식스.txt ansi noop
python ..\general_pp.py blackyak_utf8.txt ..\final\91001_브랜드의류_블랙야크.txt ansi noop
python ..\general_pp.py columbia_utf8.txt ..\final\91001_브랜드의류_컬럼비아.txt ansi noop
python ..\general_pp.py eider_utf8.txt ..\final\91001_브랜드의류_아이더.txt ansi noop
python ..\general_pp.py ellesse_utf8.txt ..\final\91001_브랜드의류_엘레쎄.txt ansi noop
python ..\general_pp.py fila_utf8.txt ..\final\91001_브랜드의류_필라.txt ansi noop
python ..\general_pp.py folder_utf8.txt ..\final\91002_브랜드신발_폴더.txt ansi noop
python ..\general_pp.py k2_utf8.txt ..\final\91001_브랜드의류_k2.txt ansi noop
python ..\general_pp.py kappa_utf8.txt ..\final\91001_브랜드의류_카파.txt ansi noop
python ..\general_pp.py kolonsport_utf8.txt ..\final\91001_브랜드의류_코오롱스포츠.txt ansi noop
python ..\general_pp.py kovea_utf8.txt ..\final\91001_브랜드의류_코베아.txt ansi noop
python ..\general_pp.py kswiss_utf8.txt ..\final\91001_브랜드의류_케이스위스.txt ansi noop
python ..\general_pp.py lafuma_utf8.txt ..\final\91001_브랜드의류_라푸마.txt ansi noop
python ..\general_pp.py lecoq_utf8.txt ..\final\91001_브랜드의류_르꼬끄.txt ansi noop
python ..\general_pp.py millet_utf8.txt ..\final\91001_브랜드의류_밀레.txt ansi noop
python ..\general_pp.py nepa_utf8.txt ..\final\91001_브랜드의류_네파.txt ansi noop
python ..\general_pp.py nike_utf8.txt ..\final\91002_브랜드신발_나이키.txt ansi noop
python ..\general_pp.py northface_utf8.txt ..\final\91001_브랜드의류_노스페이스.txt ansi noop
python ..\general_pp.py prospecs_utf8.txt ..\final\91002_브랜드신발_프로스펙스.txt ansi noop
python ..\general_pp.py puma_utf8.txt ..\final\91002_브랜드신발_푸마.txt ansi noop
python ..\general_pp.py redface_utf8.txt ..\final\91001_브랜드의류_레드페이스.txt ansi noop
python ..\general_pp.py reebok_utf8.txt ..\final\91002_브랜드신발_리복.txt ansi noop
python ..\general_pp.py shoemaker_utf8.txt ..\final\91002_브랜드신발_슈마커.txt ansi noop
python ..\general_pp.py spris_utf8.txt ..\final\91002_브랜드신발_레스모아.txt ansi noop
