python nike_v3.py > log.txt
python 네파.py >> log.txt
python 노스페이스.py >> log.txt
python 르꼬끄.py >> log.txt
python 리복.py >> log.txt
python 밀레.py >> log.txt
python 블랙야크.py >> log.txt
python 스프리스.py >> log.txt
python 아디다스.py >> log.txt
python 아식스.py >> log.txt
python 아이더.py >> log.txt
python 엘레쎄.py >> log.txt
python 카파.py >> log.txt
python 케이스위스.py >> log.txt
python 코베아.py >> log.txt
python 코오롱스포츠.py >> log.txt
python 푸마.py >> log.txt
python 프로스펙스.py >> log.txt
python 레드페이스.py >> log.txt
python k2.py >> log.txt
python 컬럼비아.py >> log.txt
python 슈마커.py >> log.txt
python 라푸마.py >> log.txt
python 폴더.py >> log.txt
python 필라.py >> log.txt
