python 7eleven.py > log.txt
python cu.py >> log.txt
python GS25.py >> log.txt
python homeplus365.py >> log.txt
python LOHBS.py >> log.txt
python ministop.py >> log.txt
python oliveyoung.py >> log.txt
python withme.py >> log.txt
//python 랄라블라_모바일사이트.py >> log.txt
