python ..\general_pp.py cgv_utf8.txt ..\final\100208_CGV.txt ansi noop
python ..\general_pp.py convention_utf8.txt ..\final\100107_컨벤션센터.txt ansi noop
python ..\general_pp.py gallery_utf8.txt ..\final\100106_소형갤러리.txt ansi ppname
//python ..\general_pp.py kofic_all_utf8.txt ..\final\100.txt ansi noop
python ..\general_pp.py kofic_other_utf8.txt ..\final\100202_영화관.txt ansi noop
python ..\general_pp.py lottecinema_utf8.txt ..\final\100209_롯데시네마.txt ansi noop
python ..\general_pp.py megabox_utf8.txt ..\final\100212_메가박스.txt ansi noop
//python ..\general_pp.py museum_all_utf8.txt ..\final\100.txt ansi noop
python ..\general_pp.py museum_art_big_utf8.txt ..\final\100104_대형미술관.txt ansi noop
python ..\general_pp.py museum_art_other_utf8.txt ..\final\100105_미술관.txt ansi noop
python ..\general_pp.py museum_big_utf8.txt ..\final\100101_대형박물관.txt ansi noop
python ..\general_pp.py museum_memorial_utf8.txt ..\final\100102_기념관.txt ansi noop
python ..\general_pp.py museum_other_utf8.txt ..\final\100103_기타박물관.txt ansi noop
python ..\general_pp.py 문화의집_2018_utf8.txt ..\final\100203_문화센터_문체부2.txt ansi noop
python ..\general_pp.py 지방문화원_2018_utf8.txt ..\final\100203_문화센터_문체부.txt ansi ppname
python ..\general_pp.py 문예회관_2018_utf8.txt ..\final\100204_대형예술센터_문체부.txt ansi ppname
python ..\general_pp.py kicaca_utf8.txt ..\final\100204_대형예술센터_문화예술회관연합회.txt ansi noop
python ..\general_pp.py stc_utf8.txt ..\final\100203_문화센터_서울연극재단.txt ansi ppname
