python ..\general_pp.py libraries_utf8.txt ..\final\200101_공공도서관2.txt ansi noop
python ..\general_pp.py libsta1_utf8.txt ..\final\200101_국립도서관.txt ansi noop
python ..\general_pp.py libsta2_utf8.txt ..\final\200101_공공도서관.txt ansi noop
python ..\general_pp.py libsta3_utf8.txt ..\final\200102_작은도서관.txt ansi noop
python ..\general_pp.py libsta4_utf8.txt ..\final\200102_기타도서관.txt ansi noop
python ..\general_pp.py smalllibrary_utf8.txt ..\final\200102_작은도서관2.txt ansi noop
python ..\general_pp.py abcmart_utf8.txt ..\final\91007_ABC마트.txt ansi noop
python ..\general_pp.py artbox_utf8.txt ..\final\90908_아트박스.txt ansi noop
python ..\general_pp.py bbq_utf8.txt ..\final\80609_비비큐치킨.txt ansi noop
python ..\general_pp.py bhc_utf8.txt ..\final\80615_비에이치씨.txt ansi noop
python ..\general_pp.py blood_house_utf8.txt ..\final\200108_헌혈의집.txt ansi noop
python ..\general_pp.py bonjuk_utf8.txt ..\final\81024_본죽.txt ansi noop
python ..\general_pp.py cleantopia_utf8.txt ..\final\91805_크린토피아.txt ansi noop
python ..\general_pp.py company_konex_utf8.txt ..\final\210203_제3시장기업.txt ansi noop
python ..\general_pp.py company_kosdaq_utf8.txt ..\final\210202_코스닥기업.txt ansi noop
python ..\general_pp.py company_kospi_utf8.txt ..\final\210201_일반상장기업.txt ansi noop
//python ..\general_pp.py driving_school2_utf8.txt ..\final\20306_자동차운전학원2.txt ansi noop
python ..\general_pp.py driving_school_utf8.txt ..\final\20306_자동차운전학원1.txt ansi noop
python ..\general_pp.py kgba_new_utf8.txt ..\final\50206_골프장CC.txt ansi noop
python ..\general_pp.py morning_glory_utf8.txt ..\final\90904_모닝글로리.txt ansi noop
python ..\general_pp.py nenechicken_new_utf8.txt ..\final\80615_네네치킨.txt ansi noop
python ..\general_pp.py pelicana_utf8.txt ..\final\80615_페리카나.txt ansi noop
python ..\general_pp.py real_estate_utf8.txt ..\final\91501_부동산.txt ansi noop
python ..\general_pp.py sme_utf8.txt ..\final\210103_중소기업.txt ansi noop
python ..\general_pp.py taekwondo_utf8.txt ..\final\20311_태권도장.txt ansi noop
python ..\general_pp.py tudari_utf8.txt ..\final\80213_투다리.txt ansi noop
python ..\general_pp.py 전국자전거보관소표준데이터_utf8.txt ..\final\220118_자전거주차장.txt ansi noop