python ..\..\general_pp.py bk_utf8.txt ..\..\final\80605_버거킹.txt ansi noop
python ..\..\general_pp.py br31_utf8.txt ..\..\final\80608_배스킨라빈스31.txt ansi noop
python ..\..\general_pp.py dunkin_utf8.txt ..\..\final\80602_던킨도너츠.txt ansi noop
python ..\..\general_pp.py goobne_utf8.txt ..\..\final\80626_굽네치킨.txt ansi noop
python ..\..\general_pp.py kfc_utf8.txt ..\..\final\80601_KFC.txt ansi noop
python ..\..\general_pp.py krispyKreme_utf8.txt ..\..\final\80627_크리스피크림도넛.txt ansi noop
python ..\..\general_pp.py kyochonchicken_utf8.txt ..\..\final\80607_교촌치킨.txt ansi noop
python ..\..\general_pp.py mac_utf8.txt ..\..\final\80604_맥도날드.txt ansi noop
python ..\..\general_pp.py momstouch_utf8.txt ..\..\final\80622_맘스터치.txt ansi noop
python ..\..\general_pp.py natuur_utf8.txt ..\..\final\80625_나뚜루.txt ansi noop
python ..\..\general_pp.py papajones_utf8.txt ..\..\final\80614_파파존스피자.txt ansi noop
python ..\..\general_pp.py popeyes_utf8.txt ..\..\final\80606_파파이스.txt ansi noop
python ..\..\general_pp.py thefrypan_utf8.txt ..\..\final\80621_더후라이팬.txt ansi noop
