python burgerking.py > log.txt
python goobne.py >> log.txt
python kfc.py >> log.txt
python krispyKreme_pp_rg.py >> log.txt
python lotteria_pp_sc.py >> log.txt
python macdonalds.py >> log.txt
python natuur_Æ÷ÅÐ¼öÁý.py >> log.txt
python papajones.py >> log.txt
python popeyes.py >> log.txt
python ±³ÃÌÄ¡Å².py >> log.txt
python ´õÈÄ¶óÀÌÆÒ.py >> log.txt
python ´øÅ²µµ³ÊÃ÷.py >> log.txt
python ¸¾½ºÅÍÄ¡.py >> log.txt
python ¹è½ºÅ²¶óºó½º.py >> log.txt
