python ..\..\general_pp.py bankofkorea_utf8.txt ..\..\final\40112_한국은행.txt ansi noop
python ..\..\general_pp.py busanbank_utf8.txt ..\..\final\40203_부산은행.txt ansi noop
python ..\..\general_pp.py citibank_utf8.txt ..\..\final\40107_한국씨티은행.txt ansi noop
python ..\..\general_pp.py daegubank_utf8.txt ..\..\final\40202_대구은행.txt ansi noop
python ..\..\general_pp.py fsb_utf8.txt ..\..\final\40305_저축은행.txt ansi noop
python ..\..\general_pp.py hanabank_utf8.txt ..\..\final\40106_KEB하나은행.txt ansi noop
python ..\..\general_pp.py hsbc_utf8.txt ..\..\final\40308_HSBC.txt ansi noop
python ..\..\general_pp.py ibkbank_utf8.txt ..\..\final\40109_기업은행.txt ansi noop
python ..\..\general_pp.py jejubank_utf8.txt ..\..\final\40204_제주은행.txt ansi noop
python ..\..\general_pp.py jeonbukbank_utf8.txt ..\..\final\40206_전북은행.txt ansi noop
python ..\..\general_pp.py kdbbank_utf8.txt ..\..\final\40306_KDB산업은행.txt ansi noop
python ..\..\general_pp.py kookmin_utf8.txt ..\..\final\40101_국민은행.txt ansi noop
python ..\..\general_pp.py koreaeximbank_utf8.txt ..\..\final\40114_한국수출입은행.txt ansi noop
python ..\..\general_pp.py kwangjubank_utf8.txt ..\..\final\40201_광주은행.txt ansi noop
python ..\..\general_pp.py kyungnambank_utf8.txt ..\..\final\40205_경남은행.txt ansi noop
python ..\..\general_pp.py nhbank_utf8.txt ..\..\final\40110_농협은행.txt ansi noop
python ..\..\general_pp.py saemaeulgeumgo_utf8.txt ..\..\final\40302_새마을금고.txt ansi noop
python ..\..\general_pp.py scbank_utf8.txt ..\..\final\40103_SC제일은행.txt ansi noop
python ..\..\general_pp.py shinhanbank_utf8.txt ..\..\final\40105_신한은행.txt ansi noop
python ..\..\general_pp.py sinhyup_utf8.txt ..\..\final\40303_신용협동조합.txt ansi noop
python ..\..\general_pp.py suhyupbank_utf8.txt ..\..\final\40307_수협은행.txt ansi noop
python ..\..\general_pp.py wooribank_utf8.txt ..\..\final\40102_우리은행.txt ansi noop
