python KDB산업은행.py > log.txt
python 경남은행.py >> log.txt
python 광주은행.py >> log.txt
python 국민은행.py >> log.txt
python 기업은행.py >> log.txt
python 농협은행.py >> log.txt
python 대구은행.py >> log.txt
python 부산은행.py >> log.txt
python 새마을금고.py >> log.txt
python 수출입은행.py >> log.txt
python 수협은행.py >> log.txt
python 신용협동조합.py >> log.txt
python 신한은행.py >> log.txt
python 씨티은행.py >> log.txt
python 우리은행.py >> log.txt
python 저축은행중앙회.py >> log.txt
python 전북은행.py >> log.txt
python 제일은행.py >> log.txt
python 제주은행.py >> log.txt
python 하나은행.py >> log.txt
python 한국은행.py >> log.txt
