python ..\..\general_pp.py costco_utf8.txt ..\..\final\90406_코스트코홀세일.txt ansi noop
python ..\..\general_pp.py emart_utf8.txt ..\..\final\90405_이마트.txt ansi noop
python ..\..\general_pp.py hanaroclub_utf8.txt ..\..\final\90410_농협하나로클럽.txt ansi noop
python ..\..\general_pp.py homeplus_utf8.txt ..\..\final\90403_홈플러스.txt ansi noop
python ..\..\general_pp.py kimsclub_utf8.txt ..\..\final\90409_킴스클럽.txt ansi noop
python ..\..\general_pp.py lottemart_toysrus_utf8.txt ..\..\final\90402_롯데마트.txt ansi noop
python ..\..\general_pp.py megamart_utf8.txt ..\..\final\90411_메가마트.txt ansi noop
python ..\..\general_pp.py savezone_utf8.txt ..\..\final\90404_세이브존.txt ansi noop
python ..\..\general_pp.py lfoutlet_utf8.txt ..\..\final\90210_아울렛_lf.txt ansi noop
python ..\..\general_pp.py etc_outlet_utf8.txt ..\..\final\90210_아울렛_기타.txt ansi noop
python ..\..\general_pp.py modaoutlet_utf8.txt ..\..\final\90210_아울렛_모다아울렛.txt ansi noop
python ..\..\general_pp.py orangefactory_utf8.txt ..\..\final\90210_아울렛_오렌지팩토리.txt ansi noop
python ..\..\general_pp.py hyundai_outlet_utf8.txt ..\..\final\90210_아울렛_현대.txt ansi noop
python ..\..\general_pp.py lotte_outlet_utf8.txt ..\..\final\90210_아울렛_롯데.txt ansi noop
python ..\..\general_pp.py nc_outlet_utf8.txt ..\..\final\90210_아울렛_이랜드계열.txt ansi noop
