python costco.py > log.txt
python emart.py >> log.txt
python hanaroclub.py >> log.txt
python lf아울렛.py >> log.txt
python NC백화점_아울렛_킴스클럽.py >> log.txt
python 롯데마트.py >> log.txt
python 롯데백화점_아울렛.py >> log.txt
python 메가마트.py >> log.txt
python 모다아울렛.py >> log.txt
python 세이브존_포털수집.py >> log.txt
python 오렌지팩토리.py >> log.txt
python 현대백화점_아울렛.py >> log.txt
python 홈플러스.py >> log.txt
