# Generated by Django 3.2.7 on 2021-09-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=10)),
                ('유형', models.CharField(max_length=20)),
                ('명칭', models.CharField(max_length=250)),
                ('nid', models.CharField(max_length=10)),
                ('lcode', models.CharField(max_length=10)),
                ('준공일', models.DateField()),
                ('구축시한', models.DateField()),
                ('실사구분', models.CharField(max_length=10)),
                ('실사일정', models.DateField(blank=True, null=True)),
                ('poi구분', models.CharField(max_length=10)),
                ('poi구축일', models.CharField(blank=True, max_length=10, null=True)),
                ('net구분', models.CharField(max_length=10)),
                ('net구축일', models.CharField(blank=True, max_length=10, null=True)),
                ('map구분', models.CharField(max_length=10)),
                ('map구축일', models.CharField(blank=True, max_length=10, null=True)),
                ('데이터확인', models.CharField(max_length=5)),
                ('서비스확인', models.CharField(max_length=5)),
                ('자료정보', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'worklist',
                'managed': False,
            },
        ),
    ]
