python ..\..\general_pp.py daeshinstock_utf8.txt ..\..\final\40504_대신증권.txt ansi noop
python ..\..\general_pp.py dongbustock_utf8.txt ..\..\final\40514_동부증권.txt ansi noop
python ..\..\general_pp.py eugenestock_utf8.txt ..\..\final\40518_유진투자증권.txt ansi noop
python ..\..\general_pp.py hana_investock_utf8.txt ..\..\final\40524_하나금융투자.txt ansi noop
python ..\..\general_pp.py hangook_investock_utf8.txt ..\..\final\40530_한국투자증권.txt ansi noop
python ..\..\general_pp.py hanwhastock_utf8.txt ..\..\final\40529_한화투자증권.txt ansi noop
python ..\..\general_pp.py hi_investstock_utf8.txt ..\..\final\40526_하이투자증권.txt ansi noop
python ..\..\general_pp.py hmcstock_utf8.txt ..\..\final\40521_HMC투자증권.txt ansi noop
python ..\..\general_pp.py kbstock_utf8.txt ..\..\final\40501_KB증권.txt ansi noop
python ..\..\general_pp.py kyobostock_utf8.txt ..\..\final\40509_교보증권.txt ansi noop
python ..\..\general_pp.py miraeassetstock_utf8.txt ..\..\final\40503_미래에셋대우증권.txt ansi noop
python ..\..\general_pp.py nhstock_utf8.txt ..\..\final\40519_NH농협증권.txt ansi noop
python ..\..\general_pp.py samsungstock_utf8.txt ..\..\final\40505_삼성증권.txt ansi noop
python ..\..\general_pp.py shinhaninvest_utf8.txt ..\..\final\40510_신한금융투자.txt ansi noop
python ..\..\general_pp.py shinyoungstock_utf8.txt ..\..\final\40520_신영증권.txt ansi noop
python ..\..\general_pp.py skstock_utf8.txt ..\..\final\40508_SK증권.txt ansi noop
python ..\..\general_pp.py stock_buguk_utf8.txt ..\..\final\40516_부국증권.txt ansi noop
python ..\..\general_pp.py stock_goldenbridge_utf8.txt ..\..\final\40517_골든브릿지투자증권.txt ansi noop
python ..\..\general_pp.py stock_hanyang_utf8.txt ..\..\final\40525_한양증권.txt ansi noop
python ..\..\general_pp.py stock_meritz_utf8.txt ..\..\final\40515_메리츠종금증권.txt ansi noop
python ..\..\general_pp.py stock_yuwha_utf8.txt ..\..\final\40523_유화증권.txt ansi noop
python ..\..\general_pp.py youantastock_utf8.txt ..\..\final\40506_유안타증권.txt ansi noop
