python °øÂ÷.py > log.txt
python ³îºÎ°è¿­_º¸½Ó_ºÎ´ëÂî°³_µîµî.py >> log.txt
python ¶Ñ·¹Áê¸£.py >> log.txt
python ·ÎÆ¼º¸ÀÌ.py >> log.txt
python »§±ÀÅÍ_Æ÷ÅÐ¼öÁý.py >> log.txt
python ½Å¶ó¸í°ú.py >> log.txt
python ½Å¼±¼³³óÅÁ.py >> log.txt
python ¾Æµþ.py >> log.txt
python ¿øÇÒ¸Ó´Ïº¸½Ó.py >> log.txt
python ÆÄ¸®¹Ù°Ô¶ß.py >> log.txt
