python ..\..\general_pp.py abllife_utf8.txt ..\..\final\40606_ABL생명.txt ansi noop
python ..\..\general_pp.py aig_utf8.txt ..\..\final\40712_차티스.txt ansi noop
python ..\..\general_pp.py heungkuklife_utf8.txt ..\..\final\40614_흥국생명.txt ansi noop
python ..\..\general_pp.py insurance_aia_utf8.txt ..\..\final\40603_AIA생명.txt ansi noop
//python ..\..\general_pp.py insurance_allianz_utf8.txt ..\..\final\40.txt ansi noop
python ..\..\general_pp.py insurance_chubblife_utf8.txt ..\..\final\40604_뉴욕생명.txt ansi noop
python ..\..\general_pp.py insurance_dgb_utf8.txt ..\..\final\40624_DBG생명.txt ansi noop
python ..\..\general_pp.py insurance_donbulife_utf8.txt ..\..\final\40616_동부생명.txt ansi noop
//python ..\..\general_pp.py insurance_dongbu_prome_utf8.txt ..\..\final\40.txt ansi noop
python ..\..\general_pp.py insurance_dongbu_utf8.txt ..\..\final\40702_동부화재.txt ansi noop
python ..\..\general_pp.py insurance_dongyanglife_utf8.txt ..\..\final\40610_동양생명.txt ansi noop
python ..\..\general_pp.py insurance_hanwhalife_utf8.txt ..\..\final\40612_한화생명.txt ansi noop
python ..\..\general_pp.py insurance_hanwha_utf8.txt ..\..\final\40710_한화손해보험.txt ansi noop
python ..\..\general_pp.py insurance_heungkuk_utf8.txt ..\..\final\40713_흥국화재.txt ansi noop
python ..\..\general_pp.py insurance_hyndai_utf8.txt ..\..\final\40703_현대해상.txt ansi noop
python ..\..\general_pp.py insurance_hyundailife_utf8.txt ..\..\final\40618_현대라이프생명.txt ansi noop
python ..\..\general_pp.py insurance_inglife_utf8.txt ..\..\final\40601_ING생명.txt ansi noop
python ..\..\general_pp.py insurance_kb_utf8.txt ..\..\final\40706_KB손해보험.txt ansi noop
python ..\..\general_pp.py insurance_kdb_utf8.txt ..\..\final\40615_KDB손해보험.txt ansi noop
python ..\..\general_pp.py insurance_lina_utf8.txt ..\..\final\40623_라이나생명.txt ansi noop
python ..\..\general_pp.py insurance_lotte_utf8.txt ..\..\final\40709_롯데보험.txt ansi noop
python ..\..\general_pp.py insurance_meritzfire_utf8.txt ..\..\final\40707_메리츠화재.txt ansi noop
python ..\..\general_pp.py insurance_metlife_utf8.txt ..\..\final\40602_메트라이프.txt ansi noop
python ..\..\general_pp.py insurance_mg_utf8.txt ..\..\final\40708_그린손해보험.txt ansi noop
python ..\..\general_pp.py insurance_miraeassetlife_utf8.txt ..\..\final\40611_미래에셋생명.txt ansi noop
//python ..\..\general_pp.py insurance_nhfire_utf8.txt ..\..\final\40.txt ansi noop
python ..\..\general_pp.py insurance_nhlife_utf8.txt ..\..\final\40625_NH농협생명.txt ansi noop
//python ..\..\general_pp.py insurance_pcalife_utf8.txt ..\..\final\40605_PCA생명.txt ansi noop
//python ..\..\general_pp.py insurance_prudential_utf8.txt ..\..\final\40.txt ansi noop
python ..\..\general_pp.py insurance_shinhanlife_utf8.txt ..\..\final\40613_신한생명.txt ansi noop
python ..\..\general_pp.py kyoboaxa_utf8.txt ..\..\final\40704_교보AXA자동차보험.txt ansi noop
python ..\..\general_pp.py kyobolife_utf8.txt ..\..\final\40609_교보생명.txt ansi noop
python ..\..\general_pp.py samsungfire_utf8.txt ..\..\final\40701_삼성화재.txt ansi noop
python ..\..\general_pp.py samsunglife_utf8.txt ..\..\final\40608_삼성생명.txt ansi noop
python ..\..\general_pp.py prudential_utf8.txt ..\..\final\40607_푸르덴셜생명.txt ansi noop
python ..\..\general_pp.py hicar_utf8.txt ..\..\final\160503_HICAR.txt ansi noop
