python ABL생명.py > log.txt
python AIA생명.py >> log.txt
python DGB생명.py >> log.txt
python ING생명.py >> log.txt
python KB손해보험.py >> log.txt
python KDB생명.py >> log.txt
python MG손해보험.py >> log.txt
python NH농협손해보험.py >> log.txt
python PCA생명.py >> log.txt
python 교보AXA.py >> log.txt
python 교보생명.py >> log.txt
python 농협생명.py >> log.txt
python 동부생명.py >> log.txt
python 동부화재.py >> log.txt
python 동부화재_프로미카월드.py >> log.txt
python 동양생명.py >> log.txt
python 롯데손해보험.py >> log.txt
python 메리츠화재.py >> log.txt
python 메트라이프생명.py >> log.txt
python 미래에셋생명.py >> log.txt
python 삼성생명.py >> log.txt
python 삼성화재.py >> log.txt
python 신한생명.py >> log.txt
python 알리안츠생명.py >> log.txt
python 처브라이프생명.py >> log.txt
python 푸르덴셜생명_포털수집.py >> log.txt
python 한화생명.py >> log.txt
python 한화손해보험.py >> log.txt
python 현대라이프생명.py >> log.txt
python 현대해상.py >> log.txt
python 흥국생명.py >> log.txt
python 흥국화재.py >> log.txt
