python ..\..\general_pp.py cafedroptop_utf8.txt ..\..\final\80719_드롭탑.txt ansi noop
python ..\..\general_pp.py cafeserio_utf8.txt ..\..\final\80703_카페쎄리오.txt ansi noop
python ..\..\general_pp.py caffebene_utf8.txt ..\..\final\80709_카페베네.txt ansi noop
python ..\..\general_pp.py caffetiamo_utf8.txt ..\..\final\80711_카페띠아모.txt ansi noop
python ..\..\general_pp.py coffeebean_utf8.txt ..\..\final\80701_커피빈.txt ansi noop
python ..\..\general_pp.py coffine_gurunaru_utf8.txt ..\..\final\80710_커핀그루나루.txt ansi noop
python ..\..\general_pp.py ediya_utf8.txt ..\..\final\80716_이디야.txt ansi noop
python ..\..\general_pp.py hollys_utf8.txt ..\..\final\80704_할리스커피.txt ansi noop
python ..\..\general_pp.py pascucci_utf8.txt ..\..\final\80705_파스쿠찌.txt ansi noop
python ..\..\general_pp.py smoothieking_utf8.txt ..\..\final\80718_스무디킹.txt ansi noop
python ..\..\general_pp.py starbucks_utf8.txt ..\..\final\80702_스타벅스.txt ansi noop
python ..\..\general_pp.py sulbing_utf8.txt ..\..\final\80720_설빙.txt ansi noop
python ..\..\general_pp.py tomntoms_utf8.txt ..\..\final\80708_탐앤탐스.txt ansi noop
python ..\..\general_pp.py twosome_utf8.txt ..\..\final\80714_투썸플레이스.txt ansi noop
python ..\..\general_pp.py yogerpresso_utf8.txt ..\..\final\80713_요거프레소.txt ansi noop
python ..\..\general_pp.py zoocoffee_utf8.txt ..\..\final\80717_주커피.txt ansi noop
