python angelinus_pp_sc.py > log.txt
python cafedroptop.py >> log.txt
python cafeserio.py >> log.txt
python cafetiamo.py >> log.txt
python caffebene.py >> log.txt
python coffine_gurunaru.py >> log.txt
python smoothieking.py >> log.txt
python starbucks.py >> log.txt
python yogerpresso.py >> log.txt
python zoocoffee.py >> log.txt
python ¼³ºù.py >> log.txt
python ÀÌµð¾ßÄ¿ÇÇ.py >> log.txt
python Ä¿ÇÇºó.py >> log.txt
python Å½¾ØÅ½½ºÄ¿ÇÇ.py >> log.txt
python Åõ½æÇÃ·¹ÀÌ½º.py >> log.txt
python ÆÄ½ºÄíÂî.py >> log.txt
python ÇÒ¸®½ºÄ¿ÇÇ.py >> log.txt
