python ..\general_pp.py audi_svc_utf8.txt ..\final\160433_아우디서비스센터.txt ansi noop
python ..\general_pp.py audi_utf8.txt ..\final\160719_아우디.txt ansi noop
python ..\general_pp.py autooasis_utf8.txt ..\final\160504_LG오토오아시스.txt ansi noop
python ..\general_pp.py benz_svc_utf8.txt ..\final\160426_벤츠서비스센터.txt ansi noop
python ..\general_pp.py benz_utf8.txt ..\final\160721_벤츠.txt ansi noop
python ..\general_pp.py bmw_svc_utf8.txt ..\final\160425_BMW서비스센터.txt ansi noop
python ..\general_pp.py bmw_utf8.txt ..\final\160710_BMW.txt ansi noop
python ..\general_pp.py bmwmini_utf8.txt ..\final\160710_BMW미니.txt ansi noop
python ..\general_pp.py cadillac_utf8.txt ..\final\160725_캐딜락.txt ansi noop
python ..\general_pp.py chevrolet_part_utf8.txt ..\final\160409_쉐보레부품대리점.txt ansi noop
python ..\general_pp.py chevrolet_svc_baro_utf8.txt ..\final\160408_쉐보레바로서비스센터.txt ansi noop
python ..\general_pp.py chevrolet_svc_other_utf8.txt ..\final\160407_쉐보레지정서비스센터.txt ansi noop
python ..\general_pp.py chevrolet_svc_utf8.txt ..\final\160408_쉐보레서비스센터.txt ansi noop
python ..\general_pp.py chevrolet_utf8.txt ..\final\160703_쉐보레.txt ansi noop
python ..\general_pp.py chrysler_utf8.txt ..\final\160713_크라이슬러.txt ansi noop
python ..\general_pp.py ferrari_svc_utf8.txt ..\final\160434_페라리서비스센터.txt ansi noop
python ..\general_pp.py ferrari_utf8.txt ..\final\160731_페라리.txt ansi noop
python ..\general_pp.py ford_utf8.txt ..\final\160720_포드.txt ansi noop
//python ..\general_pp.py hicar_utf8.txt ..\final\160503_HICAR.txt ansi noop
python ..\general_pp.py hmc_part_utf8.txt ..\final\160423_현대기아부품대리점.txt ansi noop
python ..\general_pp.py honda_utf8.txt ..\final\160712_혼다.txt ansi noop
python ..\general_pp.py hyundai_motors_svc_bluehands_utf8.txt ..\final\160405_블루핸즈.txt ansi noop
python ..\general_pp.py hyundai_motors_svc_utf8.txt ..\final\160402_현대자동차서비스센터.txt ansi noop
python ..\general_pp.py hyundai_motors_utf8.txt ..\final\160701_현대자동차.txt ansi noop
python ..\general_pp.py infinity_utf8.txt ..\final\160715_인피니티.txt ansi noop
python ..\general_pp.py jaguar_utf8.txt ..\final\160724_재규어.txt ansi noop
python ..\general_pp.py kiamotors_sales_utf8.txt ..\final\160702_기아자동차.txt ansi noop
python ..\general_pp.py kiamotors_svc_autoq_utf8.txt ..\final\160412_기아자동차오토큐.txt ansi noop
python ..\general_pp.py kiamotors_svc_utf8.txt ..\final\160410_기아자동차서비스센터.txt ansi noop
python ..\general_pp.py lamborghini_utf8.txt ..\final\160733_람보르기니.txt ansi noop
python ..\general_pp.py lexus_svc_utf8.txt ..\final\160427_렉서스서비스센터.txt ansi noop
python ..\general_pp.py lexus_utf8.txt ..\final\160711_렉서스.txt ansi noop
python ..\general_pp.py mantruck_svc_utf8.txt ..\final\160435_만트럭버스서비스센터.txt ansi noop
python ..\general_pp.py mantruck_utf8.txt ..\final\160732_만트럭버스.txt ansi noop
python ..\general_pp.py nissan_utf8.txt ..\final\160717_닛산.txt ansi noop
python ..\general_pp.py peugeot_utf8.txt ..\final\160726_푸조.txt ansi noop
python ..\general_pp.py porsche_utf8.txt ..\final\160722_포르쉐.txt ansi noop
python ..\general_pp.py speedmate_utf8.txt ..\final\160501_SK스피드메이트.txt ansi noop
python ..\general_pp.py ssangyong_motors_svc_other_utf8.txt ..\final\160415_쌍용자동차지정전문공장.txt ansi noop
python ..\general_pp.py ssangyong_motors_svc_plaza_utf8.txt ..\final\160414_쌍용자동차서비스프라자.txt ansi noop
python ..\general_pp.py ssangyong_motors_svc_utf8.txt ..\final\160413_쌍용자동차정비사업소.txt ansi noop
python ..\general_pp.py ssangyong_motors_utf8.txt ..\final\160704_쌍용자동차.txt ansi noop
python ..\general_pp.py ss_motors_utf8.txt ..\final\160705_르노삼성자동차.txt ansi noop
python ..\general_pp.py tirebank_utf8.txt ..\final\160513_타이어뱅크.txt ansi noop
python ..\general_pp.py toyota_svc_utf8.txt ..\final\160428_토요타서비스센터.txt ansi noop
python ..\general_pp.py toyota_utf8.txt ..\final\160716_토요타.txt ansi noop
python ..\general_pp.py tstation_utf8.txt ..\final\160512_T스테이션.txt ansi noop
python ..\general_pp.py volkswagen_svc_utf8.txt ..\final\160431_폭스바겐서비스센터.txt ansi noop
python ..\general_pp.py volkswagen_utf8.txt ..\final\160718_폭스바겐.txt ansi noop
python ..\general_pp.py volvo_svc_utf8.txt ..\final\160430_볼보서비스센터.txt ansi noop
python ..\general_pp.py volvo_truck_utf8.txt ..\final\160730_볼보트럭.txt ansi noop
python ..\general_pp.py volvo_utf8.txt ..\final\160714_볼보.txt ansi noop
python ..\general_pp.py zhmotors_svc_utf8.txt ..\final\160429_중한자동차서비스센터.txt ansi noop
python ..\general_pp.py zhmotors_utf8.txt ..\final\160729_중한자동차.txt ansi noop
