python audi.py > log.txt
python audi_svc.py >> log.txt
python autooasis.py >> log.txt
python benz.py >> log.txt
python bmw.py >> log.txt
python bmw_mini.py >> log.txt
python cadillac.py >> log.txt
python chevrolet.py >> log.txt
python chevrolet_part.py >> log.txt
python chevrolet_svc.py >> log.txt
python chrysler.py >> log.txt
python ford.py >> log.txt
python honda.py >> log.txt
python hyundai_motors.py >> log.txt
python hyundai_motors_svc.py >> log.txt
python Infinity.py >> log.txt
python jaguar.py >> log.txt
python kiamotors_sales.py >> log.txt
python kiamotors_svc.py >> log.txt
python nissan.py >> log.txt
python peugeot.py >> log.txt
python porsche.py >> log.txt
python speedmate.py >> log.txt
python ssangyong_motors.py >> log.txt
python ssangyong_motors_svc.py >> log.txt
python ss_motors_sales.py >> log.txt
python tirebank.py >> log.txt
python tstation.py >> log.txt
python volkswagen.py >> log.txt
python volvo.py >> log.txt
python volvo_svc.py >> log.txt
python volvo_truck.py >> log.txt
python 렉서스.py >> log.txt
python 렉서스서비스센터.py >> log.txt
python 만트럭.py >> log.txt
python 만트럭서비스센터.py >> log.txt
python 중한자동차.py >> log.txt
python 중한자동차_서비스.py >> log.txt
python 토요타.py >> log.txt
python 토요타서비스센터.py >> log.txt
python 현대기아부품대리점.py >> log.txt
